/**
Easy
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
*/
#include<stdio.h>

char findTheDifference(char* s, char* t) {
    int val=0;
    
    while (*t) {
        val += (int) *t;
        t++;
    }
    
    while (*s) {
        val -= (int) *s;
        s++;
    }
    
    return (char) val;
}


int main(void)
{
    char *s = "abcde";
    char *t = "bcadeh";
    char ans;

    ans = findTheDifference(s, t);

    printf("%c \n", ans);
}